### ISSUE TITLE
Create onboarding page 2

### ISSUE THREAD

**Issue by drewdevvv** [Firm-Collective/One-Accord#116]
![Image](https://github.com/Firm-Collective/One-Accord/assets/83799480/fb3755d4-62f6-4283-a14a-8d2c67fcc079)

**Comment by lewis-mclan** [comment]
@drewdevvv this is done, right? If so can you please close it? Thanks! :-)

**Comment by lewis-mclan** [comment]
@drewdevvv reminder! :-)
