### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by stein-key** [Firm-Collective/One-Accord#8]
**Job Story:**
When a user signs up...

**I want to collect:**
- their email so that I can validate a unique account and send notifications
- their username so that within the app they will be referred to by their unique username
- optional city and country location selection so that when they contribute activity Launch Day the map will light up

I want them to opt into notification settings and understand which notifications will help them participate in the Launch day event.

I want them to accept Terms of Use and Privacy Policy Agreements

**Comment by jevens007** [comment]
Should year of birth be asked to identify in the user is under 18? Are there protections needed for youth/children? Can their posts appear on the public feed with their city/location (might be a concern for some parents)

**Comment by drewdevvv** [comment]
Team Orange would like this epic

**Comment by Jmoody22** [comment]
Since you want to offer text notifications, we might want to also request a phone# during registration.

**Comment by drewdevvv** [comment]
Industry standard for social media apps are age 13 in the U.S. There doesn't seem to be a restriction on apps that don't have negative risks or a proliferation of community toxicity. That brings up another issue, of sanitizing and creating a community guideline for language for inputs. This can also pose the risk of preventing goodwill users from being able to submit for something silly like a translation error.
